name: first-github-action
on: [push]
    branches:
    - master 
jobs:
  compile_job:
    runs-on: [self-hosted, Windows, X64, laba_4]
    steps:
      - name: Display the path
        run: echo ${env:PATH}
        shell: powershell
        continue-on-error: true