name: Test-Game-Compile
on: 
 push:
jobs:
  compile_job:
    runs-on: [self-hosted, Windows, X64, laba_4]
    steps:
     - name: Display the path
       run: 'C:\_tmptmp>RPGMPacker-Windows.exe -v'
       shell: powershell
       continue-on-error: true